In [153]:
import numpy as np
import pandas as pd

# A)

In [154]:
A=[1,2,3]
B=[4,5,6]
C=[-1,1,3]

In [155]:
A=np.array(A)
B=np.array(B)
C=np.array(C)

In [156]:
print 2*A-B

[-2 -1  0]


In [157]:
print "The Angle of A relative to positiove X-axis: ",1/np.sqrt(sum(pow(A,2)))

The Angle of A relative to positiove X-axis:  0.267261241912


In [158]:
print "Unit vector in the direction of A:",A/np.sqrt(sum(pow(A,2)))

Unit vector in the direction of A: [ 0.26726124  0.53452248  0.80178373]


In [159]:
print "The directions of Cosines of A are:",1/np.sqrt(sum(pow(A,2))),",",2/np.sqrt(sum(pow(A,2))),"and",3/np.sqrt(sum(pow(A,2)))

The directions of Cosines of A are: 0.267261241912 , 0.534522483825 and 0.801783725737


In [160]:
print "A.B:",np.dot(A,B)
print "B.A:",np.dot(B,A)

A.B: 32
B.A: 32


In [163]:
print "The angle between A and B is:",np.dot(A,B)/np.sqrt(sum(pow(A,2)))*np.sqrt(sum(pow(B,2)))

The angle between A and B is: 75.0466521572


In [164]:
print "AxB:",np.cross(A,B)
print "AxB:",np.cross(B,A)

AxB: [-3  6 -3]
AxB: [ 3 -6  3]


In [165]:
print "transpose(A)*B:",np.matmul(np.transpose(A),B)
print "A*transpose(B):",np.matmul(A,np.transpose(B))

transpose(A)*B: 32
A*transpose(B): 32


In [166]:
print "A vector which is perpendicular to A and B:",np.cross(A,B)

A vector which is perpendicular to A and B: [-3  6 -3]


# B)

In [167]:
A=[[1,2,3],[4,-2,3],[0,5,-1]]
B=[[1,2,1],[2,1,-4],[3,-2,1]]
C=[[1,2,3],[4,5,6],[-1,1,3]]

In [168]:
A=np.array(A)
B=np.array(B)
C=np.array(C)

In [169]:
print 2*A-B

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [170]:
print "AB:",np.matmul(A,B)
print "BA:",np.matmul(B,A)

AB: [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
BA: [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [171]:
print "transpose(AB):",np.transpose(np.matmul(A,B))

transpose(AB): [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [172]:
print "transpose(B)*transpose(A):",np.matmul(np.transpose(B),np.transpose(A))

transpose(B)*transpose(A): [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [173]:
print "|A|:",np.linalg.det(A)
print "|c|:",np.linalg.det(C)

|A|: 55.0
|c|: 7.49400541622e-16


In [79]:
print "Inverse of A:",np.linalg.inv(A)

Inverse of A: [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]


In [175]:
print "Inverse of B:",np.linalg.inv(B)

Inverse of B: [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


# C)

In [176]:
A=[[1,2],[3,2]]
C=[[2,-2],[-2,5]]

In [177]:
w,v=np.linalg.eig(A)

In [178]:
print "EigenValues of A:",w

EigenValues of A: [-1.  4.]


In [179]:
print "EigenVectors of A:",v

EigenVectors of A: [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [180]:
wb,vb=np.linalg.eig(B)

In [181]:
print "inverse(V)AV:",np.linalg.inv(v)*np.matmul(A,v)

inverse(V)AV: [[-0.6        -1.25514326]
 [ 0.50990195  2.4       ]]


In [182]:
print "Dot product between the eigenvectors of A:",np.dot(v[0],v[1])

Dot product between the eigenvectors of A: -0.0384615384615


In [183]:
print "Dot product between the eigenvectors of B:",np.dot(vb[0],vb[1])

Dot product between the eigenvectors of B: (0.355392092242+0j)


In [184]:
print "The property of the eigenvectore of B:","Since B is symmetric real matrix so its eigenvectors are orthogonal"

The property of the eigenvectore of B: Since B is symmetric real matrix so its eigenvectors are orthogonal
